<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Click image below to see failed test Screenshot]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Oct_29_19_27_28_IST_2021.jpg><img src=Fri_Oct_29_19_27_28_IST_2021.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click image below to see failed test Screenshot]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Oct_29_19_27_30_IST_2021.jpg><img src=Fri_Oct_29_19_27_30_IST_2021.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2021-10-29T13:57:24Z" name="Data Driven Basics" finished-at="2021-10-29T13:57:30Z" duration-ms="6220">
    <groups>
    </groups>
    <test started-at="2021-10-29T13:57:24Z" name="Login-Test" finished-at="2021-10-29T13:57:29Z" duration-ms="5019">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method signature="bankManagerLoginTest()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@126945f9]" started-at="2021-10-29T13:57:24Z" name="bankManagerLoginTest" finished-at="2021-10-29T13:57:28Z" duration-ms="4425" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not successful
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.BankManagerLoginTest.bankManagerLoginTest(BankManagerLoginTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click image below to see failed test Screenshot]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Oct_29_19_27_28_IST_2021.jpg><img src=Fri_Oct_29_19_27_28_IST_2021.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- bankManagerLoginTest -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Login-Test -->
    <test started-at="2021-10-29T13:57:29Z" name="Add-Customer_Test" finished-at="2021-10-29T13:57:30Z" duration-ms="1176">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@66565121]" started-at="2021-10-29T13:57:18Z" name="setUp" finished-at="2021-10-29T13:57:24Z" duration-ms="5724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@66565121]" started-at="2021-10-29T13:57:29Z" name="addCustomer" data-provider="getData" finished-at="2021-10-29T13:57:29Z" duration-ms="605" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[wuh24bkf]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer was not added]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer was not added
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click image below to see failed test Screenshot]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Oct_29_19_27_30_IST_2021.jpg><img src=Fri_Oct_29_19_27_30_IST_2021.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add-Customer_Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
